/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "LED.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	LedInit(LED_PIN_GREEN);
	LedInit(LED_PIN_ORANGE);
	LedInit(LED_PIN_RED);
	LedInit(LED_PIN_BLUE);

	while(1)
	{
		LedBlink(LED_PIN_GREEN,200);
//		DelayMs(200);
		LedBlink(LED_PIN_ORANGE,200);
//		DelayMs(200);
		LedBlink(LED_PIN_RED,200);
//		DelayMs(200);
		LedBlink(LED_PIN_BLUE,200);
		DelayMs(200);
	}
	return 0;
}
